services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    environment:
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
      - DOMAIN=${DOMAIN}
    depends_on:
      - frontend
    networks:
      gc:
        aliases:
          - nginx
    volumes:
      - certs:/etc/letsencrypt
      - uploads:/var/www/images
      - frontend_vol:/var/www/frontend/
    ports:
      - '80:80'
      - '443:443'

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: ${VITE_API_URL}
        VITE_UPLOADS_PATH: ${VITE_UPLOADS_PATH}
    depends_on:
      - backend
    networks:
      gc:
        aliases:
          - frontend
    volumes:
      - frontend_vol:/app/dist

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL
      - JWT_SECRET
      - ADMIN_PASSWORD
    volumes:
      - uploads:/app/uploads
    depends_on:
      - database
    networks:
      gc:
        aliases:
          - backend
    ports:
      - '3000:3000'

  database:
    image: postgres:15
    networks:
      gc:
        aliases:
          - database
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

networks:
  gc:

volumes:
  db_data:
    name: db_data
  uploads:
    name: uploads
  frontend_vol:
    name: frontend_vol
  certs:
    name: certs
